//C++ Abstract Syntax Implementation generated by the BNF Converter.
#include <algorithm>
#include <string>
#include <vector>
#include "Absyn.H"
namespace parser
{
/********************   PDefs    ********************/
PDefs::PDefs(ListDef *p1)
{
  listdef_ = p1;

}

PDefs::PDefs(const PDefs & other)
{
  listdef_ = other.listdef_->clone();

}

PDefs &PDefs::operator=(const PDefs & other)
{
  PDefs tmp(other);
  swap(tmp);
  return *this;
}

void PDefs::swap(PDefs & other)
{
  std::swap(listdef_, other.listdef_);

}

PDefs::~PDefs()
{
  delete(listdef_);

}

void PDefs::accept(Visitor *v)
{
  v->visitPDefs(this);
}

PDefs *PDefs::clone() const
{
  return new PDefs(*this);
}



/********************   DFun    ********************/
DFun::DFun(Type *p1, Ident p2, ListArg *p3, ListStm *p4)
{
  type_ = p1;
  ident_ = p2;
  listarg_ = p3;
  liststm_ = p4;

}

DFun::DFun(const DFun & other)
{
  type_ = other.type_->clone();
  ident_ = other.ident_;
  listarg_ = other.listarg_->clone();
  liststm_ = other.liststm_->clone();

}

DFun &DFun::operator=(const DFun & other)
{
  DFun tmp(other);
  swap(tmp);
  return *this;
}

void DFun::swap(DFun & other)
{
  std::swap(type_, other.type_);
  std::swap(ident_, other.ident_);
  std::swap(listarg_, other.listarg_);
  std::swap(liststm_, other.liststm_);

}

DFun::~DFun()
{
  delete(type_);
  delete(listarg_);
  delete(liststm_);

}

void DFun::accept(Visitor *v)
{
  v->visitDFun(this);
}

DFun *DFun::clone() const
{
  return new DFun(*this);
}



/********************   DPointer    ********************/
DPointer::DPointer(Ident p1, Ident p2)
{
  ident_1 = p1;
  ident_2 = p2;

}

DPointer::DPointer(const DPointer & other)
{
  ident_1 = other.ident_1;
  ident_2 = other.ident_2;

}

DPointer &DPointer::operator=(const DPointer & other)
{
  DPointer tmp(other);
  swap(tmp);
  return *this;
}

void DPointer::swap(DPointer & other)
{
  std::swap(ident_1, other.ident_1);
  std::swap(ident_2, other.ident_2);

}

DPointer::~DPointer()
{

}

void DPointer::accept(Visitor *v)
{
  v->visitDPointer(this);
}

DPointer *DPointer::clone() const
{
  return new DPointer(*this);
}



/********************   DStruct    ********************/
DStruct::DStruct(Struct *p1)
{
  struct_ = p1;

}

DStruct::DStruct(const DStruct & other)
{
  struct_ = other.struct_->clone();

}

DStruct &DStruct::operator=(const DStruct & other)
{
  DStruct tmp(other);
  swap(tmp);
  return *this;
}

void DStruct::swap(DStruct & other)
{
  std::swap(struct_, other.struct_);

}

DStruct::~DStruct()
{
  delete(struct_);

}

void DStruct::accept(Visitor *v)
{
  v->visitDStruct(this);
}

DStruct *DStruct::clone() const
{
  return new DStruct(*this);
}



/********************   DInlinePointer    ********************/
DInlinePointer::DInlinePointer(Struct *p1, Ident p2)
{
  struct_ = p1;
  ident_ = p2;

}

DInlinePointer::DInlinePointer(const DInlinePointer & other)
{
  struct_ = other.struct_->clone();
  ident_ = other.ident_;

}

DInlinePointer &DInlinePointer::operator=(const DInlinePointer & other)
{
  DInlinePointer tmp(other);
  swap(tmp);
  return *this;
}

void DInlinePointer::swap(DInlinePointer & other)
{
  std::swap(struct_, other.struct_);
  std::swap(ident_, other.ident_);

}

DInlinePointer::~DInlinePointer()
{
  delete(struct_);

}

void DInlinePointer::accept(Visitor *v)
{
  v->visitDInlinePointer(this);
}

DInlinePointer *DInlinePointer::clone() const
{
  return new DInlinePointer(*this);
}



/********************   DClass    ********************/
DClass::DClass(Ident p1, ListMember *p2)
{
  ident_ = p1;
  listmember_ = p2;

}

DClass::DClass(const DClass & other)
{
  ident_ = other.ident_;
  listmember_ = other.listmember_->clone();

}

DClass &DClass::operator=(const DClass & other)
{
  DClass tmp(other);
  swap(tmp);
  return *this;
}

void DClass::swap(DClass & other)
{
  std::swap(ident_, other.ident_);
  std::swap(listmember_, other.listmember_);

}

DClass::~DClass()
{
  delete(listmember_);

}

void DClass::accept(Visitor *v)
{
  v->visitDClass(this);
}

DClass *DClass::clone() const
{
  return new DClass(*this);
}



/********************   DSubclass    ********************/
DSubclass::DSubclass(Ident p1, Ident p2, ListMember *p3)
{
  ident_1 = p1;
  ident_2 = p2;
  listmember_ = p3;

}

DSubclass::DSubclass(const DSubclass & other)
{
  ident_1 = other.ident_1;
  ident_2 = other.ident_2;
  listmember_ = other.listmember_->clone();

}

DSubclass &DSubclass::operator=(const DSubclass & other)
{
  DSubclass tmp(other);
  swap(tmp);
  return *this;
}

void DSubclass::swap(DSubclass & other)
{
  std::swap(ident_1, other.ident_1);
  std::swap(ident_2, other.ident_2);
  std::swap(listmember_, other.listmember_);

}

DSubclass::~DSubclass()
{
  delete(listmember_);

}

void DSubclass::accept(Visitor *v)
{
  v->visitDSubclass(this);
}

DSubclass *DSubclass::clone() const
{
  return new DSubclass(*this);
}



/********************   ADecl    ********************/
ADecl::ADecl(Type *p1, Ident p2)
{
  type_ = p1;
  ident_ = p2;

}

ADecl::ADecl(const ADecl & other)
{
  type_ = other.type_->clone();
  ident_ = other.ident_;

}

ADecl &ADecl::operator=(const ADecl & other)
{
  ADecl tmp(other);
  swap(tmp);
  return *this;
}

void ADecl::swap(ADecl & other)
{
  std::swap(type_, other.type_);
  std::swap(ident_, other.ident_);

}

ADecl::~ADecl()
{
  delete(type_);

}

void ADecl::accept(Visitor *v)
{
  v->visitADecl(this);
}

ADecl *ADecl::clone() const
{
  return new ADecl(*this);
}



/********************   SEmpty    ********************/
SEmpty::SEmpty()
{

}

SEmpty::SEmpty(const SEmpty & other)
{

}

SEmpty &SEmpty::operator=(const SEmpty & other)
{
  SEmpty tmp(other);
  swap(tmp);
  return *this;
}

void SEmpty::swap(SEmpty & other)
{

}

SEmpty::~SEmpty()
{

}

void SEmpty::accept(Visitor *v)
{
  v->visitSEmpty(this);
}

SEmpty *SEmpty::clone() const
{
  return new SEmpty(*this);
}



/********************   SBlock    ********************/
SBlock::SBlock(ListStm *p1)
{
  liststm_ = p1;

}

SBlock::SBlock(const SBlock & other)
{
  liststm_ = other.liststm_->clone();

}

SBlock &SBlock::operator=(const SBlock & other)
{
  SBlock tmp(other);
  swap(tmp);
  return *this;
}

void SBlock::swap(SBlock & other)
{
  std::swap(liststm_, other.liststm_);

}

SBlock::~SBlock()
{
  delete(liststm_);

}

void SBlock::accept(Visitor *v)
{
  v->visitSBlock(this);
}

SBlock *SBlock::clone() const
{
  return new SBlock(*this);
}



/********************   SDecl    ********************/
SDecl::SDecl(Type *p1, ListDec *p2)
{
  type_ = p1;
  listdec_ = p2;

}

SDecl::SDecl(const SDecl & other)
{
  type_ = other.type_->clone();
  listdec_ = other.listdec_->clone();

}

SDecl &SDecl::operator=(const SDecl & other)
{
  SDecl tmp(other);
  swap(tmp);
  return *this;
}

void SDecl::swap(SDecl & other)
{
  std::swap(type_, other.type_);
  std::swap(listdec_, other.listdec_);

}

SDecl::~SDecl()
{
  delete(type_);
  delete(listdec_);

}

void SDecl::accept(Visitor *v)
{
  v->visitSDecl(this);
}

SDecl *SDecl::clone() const
{
  return new SDecl(*this);
}



/********************   SAss    ********************/
SAss::SAss(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

SAss::SAss(const SAss & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

SAss &SAss::operator=(const SAss & other)
{
  SAss tmp(other);
  swap(tmp);
  return *this;
}

void SAss::swap(SAss & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

SAss::~SAss()
{
  delete(exp_1);
  delete(exp_2);

}

void SAss::accept(Visitor *v)
{
  v->visitSAss(this);
}

SAss *SAss::clone() const
{
  return new SAss(*this);
}



/********************   SIncr    ********************/
SIncr::SIncr(Exp *p1)
{
  exp_ = p1;

}

SIncr::SIncr(const SIncr & other)
{
  exp_ = other.exp_->clone();

}

SIncr &SIncr::operator=(const SIncr & other)
{
  SIncr tmp(other);
  swap(tmp);
  return *this;
}

void SIncr::swap(SIncr & other)
{
  std::swap(exp_, other.exp_);

}

SIncr::~SIncr()
{
  delete(exp_);

}

void SIncr::accept(Visitor *v)
{
  v->visitSIncr(this);
}

SIncr *SIncr::clone() const
{
  return new SIncr(*this);
}



/********************   SDecr    ********************/
SDecr::SDecr(Exp *p1)
{
  exp_ = p1;

}

SDecr::SDecr(const SDecr & other)
{
  exp_ = other.exp_->clone();

}

SDecr &SDecr::operator=(const SDecr & other)
{
  SDecr tmp(other);
  swap(tmp);
  return *this;
}

void SDecr::swap(SDecr & other)
{
  std::swap(exp_, other.exp_);

}

SDecr::~SDecr()
{
  delete(exp_);

}

void SDecr::accept(Visitor *v)
{
  v->visitSDecr(this);
}

SDecr *SDecr::clone() const
{
  return new SDecr(*this);
}



/********************   SRet    ********************/
SRet::SRet(Exp *p1)
{
  exp_ = p1;

}

SRet::SRet(const SRet & other)
{
  exp_ = other.exp_->clone();

}

SRet &SRet::operator=(const SRet & other)
{
  SRet tmp(other);
  swap(tmp);
  return *this;
}

void SRet::swap(SRet & other)
{
  std::swap(exp_, other.exp_);

}

SRet::~SRet()
{
  delete(exp_);

}

void SRet::accept(Visitor *v)
{
  v->visitSRet(this);
}

SRet *SRet::clone() const
{
  return new SRet(*this);
}



/********************   SVRet    ********************/
SVRet::SVRet()
{

}

SVRet::SVRet(const SVRet & other)
{

}

SVRet &SVRet::operator=(const SVRet & other)
{
  SVRet tmp(other);
  swap(tmp);
  return *this;
}

void SVRet::swap(SVRet & other)
{

}

SVRet::~SVRet()
{

}

void SVRet::accept(Visitor *v)
{
  v->visitSVRet(this);
}

SVRet *SVRet::clone() const
{
  return new SVRet(*this);
}



/********************   SCond    ********************/
SCond::SCond(Exp *p1, Stm *p2)
{
  exp_ = p1;
  stm_ = p2;

}

SCond::SCond(const SCond & other)
{
  exp_ = other.exp_->clone();
  stm_ = other.stm_->clone();

}

SCond &SCond::operator=(const SCond & other)
{
  SCond tmp(other);
  swap(tmp);
  return *this;
}

void SCond::swap(SCond & other)
{
  std::swap(exp_, other.exp_);
  std::swap(stm_, other.stm_);

}

SCond::~SCond()
{
  delete(exp_);
  delete(stm_);

}

void SCond::accept(Visitor *v)
{
  v->visitSCond(this);
}

SCond *SCond::clone() const
{
  return new SCond(*this);
}



/********************   SCondElse    ********************/
SCondElse::SCondElse(Exp *p1, Stm *p2, Stm *p3)
{
  exp_ = p1;
  stm_1 = p2;
  stm_2 = p3;

}

SCondElse::SCondElse(const SCondElse & other)
{
  exp_ = other.exp_->clone();
  stm_1 = other.stm_1->clone();
  stm_2 = other.stm_2->clone();

}

SCondElse &SCondElse::operator=(const SCondElse & other)
{
  SCondElse tmp(other);
  swap(tmp);
  return *this;
}

void SCondElse::swap(SCondElse & other)
{
  std::swap(exp_, other.exp_);
  std::swap(stm_1, other.stm_1);
  std::swap(stm_2, other.stm_2);

}

SCondElse::~SCondElse()
{
  delete(exp_);
  delete(stm_1);
  delete(stm_2);

}

void SCondElse::accept(Visitor *v)
{
  v->visitSCondElse(this);
}

SCondElse *SCondElse::clone() const
{
  return new SCondElse(*this);
}



/********************   SWhile    ********************/
SWhile::SWhile(Exp *p1, Stm *p2)
{
  exp_ = p1;
  stm_ = p2;

}

SWhile::SWhile(const SWhile & other)
{
  exp_ = other.exp_->clone();
  stm_ = other.stm_->clone();

}

SWhile &SWhile::operator=(const SWhile & other)
{
  SWhile tmp(other);
  swap(tmp);
  return *this;
}

void SWhile::swap(SWhile & other)
{
  std::swap(exp_, other.exp_);
  std::swap(stm_, other.stm_);

}

SWhile::~SWhile()
{
  delete(exp_);
  delete(stm_);

}

void SWhile::accept(Visitor *v)
{
  v->visitSWhile(this);
}

SWhile *SWhile::clone() const
{
  return new SWhile(*this);
}



/********************   SExp    ********************/
SExp::SExp(Exp *p1)
{
  exp_ = p1;

}

SExp::SExp(const SExp & other)
{
  exp_ = other.exp_->clone();

}

SExp &SExp::operator=(const SExp & other)
{
  SExp tmp(other);
  swap(tmp);
  return *this;
}

void SExp::swap(SExp & other)
{
  std::swap(exp_, other.exp_);

}

SExp::~SExp()
{
  delete(exp_);

}

void SExp::accept(Visitor *v)
{
  v->visitSExp(this);
}

SExp *SExp::clone() const
{
  return new SExp(*this);
}



/********************   SForEach    ********************/
SForEach::SForEach(Type *p1, Ident p2, Exp *p3, Stm *p4)
{
  type_ = p1;
  ident_ = p2;
  exp_ = p3;
  stm_ = p4;

}

SForEach::SForEach(const SForEach & other)
{
  type_ = other.type_->clone();
  ident_ = other.ident_;
  exp_ = other.exp_->clone();
  stm_ = other.stm_->clone();

}

SForEach &SForEach::operator=(const SForEach & other)
{
  SForEach tmp(other);
  swap(tmp);
  return *this;
}

void SForEach::swap(SForEach & other)
{
  std::swap(type_, other.type_);
  std::swap(ident_, other.ident_);
  std::swap(exp_, other.exp_);
  std::swap(stm_, other.stm_);

}

SForEach::~SForEach()
{
  delete(type_);
  delete(exp_);
  delete(stm_);

}

void SForEach::accept(Visitor *v)
{
  v->visitSForEach(this);
}

SForEach *SForEach::clone() const
{
  return new SForEach(*this);
}



/********************   DecNoInit    ********************/
DecNoInit::DecNoInit(Ident p1)
{
  ident_ = p1;

}

DecNoInit::DecNoInit(const DecNoInit & other)
{
  ident_ = other.ident_;

}

DecNoInit &DecNoInit::operator=(const DecNoInit & other)
{
  DecNoInit tmp(other);
  swap(tmp);
  return *this;
}

void DecNoInit::swap(DecNoInit & other)
{
  std::swap(ident_, other.ident_);

}

DecNoInit::~DecNoInit()
{

}

void DecNoInit::accept(Visitor *v)
{
  v->visitDecNoInit(this);
}

DecNoInit *DecNoInit::clone() const
{
  return new DecNoInit(*this);
}



/********************   DecInit    ********************/
DecInit::DecInit(Ident p1, Exp *p2)
{
  ident_ = p1;
  exp_ = p2;

}

DecInit::DecInit(const DecInit & other)
{
  ident_ = other.ident_;
  exp_ = other.exp_->clone();

}

DecInit &DecInit::operator=(const DecInit & other)
{
  DecInit tmp(other);
  swap(tmp);
  return *this;
}

void DecInit::swap(DecInit & other)
{
  std::swap(ident_, other.ident_);
  std::swap(exp_, other.exp_);

}

DecInit::~DecInit()
{
  delete(exp_);

}

void DecInit::accept(Visitor *v)
{
  v->visitDecInit(this);
}

DecInit *DecInit::clone() const
{
  return new DecInit(*this);
}



/********************   TInt    ********************/
TInt::TInt()
{

}

TInt::TInt(const TInt & other)
{

}

TInt &TInt::operator=(const TInt & other)
{
  TInt tmp(other);
  swap(tmp);
  return *this;
}

void TInt::swap(TInt & other)
{

}

TInt::~TInt()
{

}

void TInt::accept(Visitor *v)
{
  v->visitTInt(this);
}

TInt *TInt::clone() const
{
  return new TInt(*this);
}



/********************   TDouble    ********************/
TDouble::TDouble()
{

}

TDouble::TDouble(const TDouble & other)
{

}

TDouble &TDouble::operator=(const TDouble & other)
{
  TDouble tmp(other);
  swap(tmp);
  return *this;
}

void TDouble::swap(TDouble & other)
{

}

TDouble::~TDouble()
{

}

void TDouble::accept(Visitor *v)
{
  v->visitTDouble(this);
}

TDouble *TDouble::clone() const
{
  return new TDouble(*this);
}



/********************   TBool    ********************/
TBool::TBool()
{

}

TBool::TBool(const TBool & other)
{

}

TBool &TBool::operator=(const TBool & other)
{
  TBool tmp(other);
  swap(tmp);
  return *this;
}

void TBool::swap(TBool & other)
{

}

TBool::~TBool()
{

}

void TBool::accept(Visitor *v)
{
  v->visitTBool(this);
}

TBool *TBool::clone() const
{
  return new TBool(*this);
}



/********************   TVoid    ********************/
TVoid::TVoid()
{

}

TVoid::TVoid(const TVoid & other)
{

}

TVoid &TVoid::operator=(const TVoid & other)
{
  TVoid tmp(other);
  swap(tmp);
  return *this;
}

void TVoid::swap(TVoid & other)
{

}

TVoid::~TVoid()
{

}

void TVoid::accept(Visitor *v)
{
  v->visitTVoid(this);
}

TVoid *TVoid::clone() const
{
  return new TVoid(*this);
}



/********************   TStr    ********************/
TStr::TStr()
{

}

TStr::TStr(const TStr & other)
{

}

TStr &TStr::operator=(const TStr & other)
{
  TStr tmp(other);
  swap(tmp);
  return *this;
}

void TStr::swap(TStr & other)
{

}

TStr::~TStr()
{

}

void TStr::accept(Visitor *v)
{
  v->visitTStr(this);
}

TStr *TStr::clone() const
{
  return new TStr(*this);
}



/********************   TFun    ********************/
TFun::TFun(Type *p1, ListType *p2)
{
  type_ = p1;
  listtype_ = p2;

}

TFun::TFun(const TFun & other)
{
  type_ = other.type_->clone();
  listtype_ = other.listtype_->clone();

}

TFun &TFun::operator=(const TFun & other)
{
  TFun tmp(other);
  swap(tmp);
  return *this;
}

void TFun::swap(TFun & other)
{
  std::swap(type_, other.type_);
  std::swap(listtype_, other.listtype_);

}

TFun::~TFun()
{
  delete(type_);
  delete(listtype_);

}

void TFun::accept(Visitor *v)
{
  v->visitTFun(this);
}

TFun *TFun::clone() const
{
  return new TFun(*this);
}



/********************   TArray    ********************/
TArray::TArray(Type *p1)
{
  type_ = p1;

}

TArray::TArray(const TArray & other)
{
  type_ = other.type_->clone();

}

TArray &TArray::operator=(const TArray & other)
{
  TArray tmp(other);
  swap(tmp);
  return *this;
}

void TArray::swap(TArray & other)
{
  std::swap(type_, other.type_);

}

TArray::~TArray()
{
  delete(type_);

}

void TArray::accept(Visitor *v)
{
  v->visitTArray(this);
}

TArray *TArray::clone() const
{
  return new TArray(*this);
}



/********************   TIdent    ********************/
TIdent::TIdent(Ident p1)
{
  ident_ = p1;

}

TIdent::TIdent(const TIdent & other)
{
  ident_ = other.ident_;

}

TIdent &TIdent::operator=(const TIdent & other)
{
  TIdent tmp(other);
  swap(tmp);
  return *this;
}

void TIdent::swap(TIdent & other)
{
  std::swap(ident_, other.ident_);

}

TIdent::~TIdent()
{

}

void TIdent::accept(Visitor *v)
{
  v->visitTIdent(this);
}

TIdent *TIdent::clone() const
{
  return new TIdent(*this);
}



/********************   TPointer    ********************/
TPointer::TPointer(Ident p1)
{
  ident_ = p1;

}

TPointer::TPointer(const TPointer & other)
{
  ident_ = other.ident_;

}

TPointer &TPointer::operator=(const TPointer & other)
{
  TPointer tmp(other);
  swap(tmp);
  return *this;
}

void TPointer::swap(TPointer & other)
{
  std::swap(ident_, other.ident_);

}

TPointer::~TPointer()
{

}

void TPointer::accept(Visitor *v)
{
  v->visitTPointer(this);
}

TPointer *TPointer::clone() const
{
  return new TPointer(*this);
}



/********************   TStruct    ********************/
TStruct::TStruct(Ident p1)
{
  ident_ = p1;

}

TStruct::TStruct(const TStruct & other)
{
  ident_ = other.ident_;

}

TStruct &TStruct::operator=(const TStruct & other)
{
  TStruct tmp(other);
  swap(tmp);
  return *this;
}

void TStruct::swap(TStruct & other)
{
  std::swap(ident_, other.ident_);

}

TStruct::~TStruct()
{

}

void TStruct::accept(Visitor *v)
{
  v->visitTStruct(this);
}

TStruct *TStruct::clone() const
{
  return new TStruct(*this);
}



/********************   TClass    ********************/
TClass::TClass(Ident p1)
{
  ident_ = p1;

}

TClass::TClass(const TClass & other)
{
  ident_ = other.ident_;

}

TClass &TClass::operator=(const TClass & other)
{
  TClass tmp(other);
  swap(tmp);
  return *this;
}

void TClass::swap(TClass & other)
{
  std::swap(ident_, other.ident_);

}

TClass::~TClass()
{

}

void TClass::accept(Visitor *v)
{
  v->visitTClass(this);
}

TClass *TClass::clone() const
{
  return new TClass(*this);
}



/********************   EVar    ********************/
EVar::EVar(Ident p1)
{
  ident_ = p1;

}

EVar::EVar(const EVar & other)
{
  ident_ = other.ident_;

}

EVar &EVar::operator=(const EVar & other)
{
  EVar tmp(other);
  swap(tmp);
  return *this;
}

void EVar::swap(EVar & other)
{
  std::swap(ident_, other.ident_);

}

EVar::~EVar()
{

}

void EVar::accept(Visitor *v)
{
  v->visitEVar(this);
}

EVar *EVar::clone() const
{
  return new EVar(*this);
}



/********************   EApp    ********************/
EApp::EApp(Ident p1, ListExp *p2)
{
  ident_ = p1;
  listexp_ = p2;

}

EApp::EApp(const EApp & other)
{
  ident_ = other.ident_;
  listexp_ = other.listexp_->clone();

}

EApp &EApp::operator=(const EApp & other)
{
  EApp tmp(other);
  swap(tmp);
  return *this;
}

void EApp::swap(EApp & other)
{
  std::swap(ident_, other.ident_);
  std::swap(listexp_, other.listexp_);

}

EApp::~EApp()
{
  delete(listexp_);

}

void EApp::accept(Visitor *v)
{
  v->visitEApp(this);
}

EApp *EApp::clone() const
{
  return new EApp(*this);
}



/********************   EInt    ********************/
EInt::EInt(Integer p1)
{
  integer_ = p1;

}

EInt::EInt(const EInt & other)
{
  integer_ = other.integer_;

}

EInt &EInt::operator=(const EInt & other)
{
  EInt tmp(other);
  swap(tmp);
  return *this;
}

void EInt::swap(EInt & other)
{
  std::swap(integer_, other.integer_);

}

EInt::~EInt()
{

}

void EInt::accept(Visitor *v)
{
  v->visitEInt(this);
}

EInt *EInt::clone() const
{
  return new EInt(*this);
}



/********************   EDouble    ********************/
EDouble::EDouble(Double p1)
{
  double_ = p1;

}

EDouble::EDouble(const EDouble & other)
{
  double_ = other.double_;

}

EDouble &EDouble::operator=(const EDouble & other)
{
  EDouble tmp(other);
  swap(tmp);
  return *this;
}

void EDouble::swap(EDouble & other)
{
  std::swap(double_, other.double_);

}

EDouble::~EDouble()
{

}

void EDouble::accept(Visitor *v)
{
  v->visitEDouble(this);
}

EDouble *EDouble::clone() const
{
  return new EDouble(*this);
}



/********************   ELitTrue    ********************/
ELitTrue::ELitTrue()
{

}

ELitTrue::ELitTrue(const ELitTrue & other)
{

}

ELitTrue &ELitTrue::operator=(const ELitTrue & other)
{
  ELitTrue tmp(other);
  swap(tmp);
  return *this;
}

void ELitTrue::swap(ELitTrue & other)
{

}

ELitTrue::~ELitTrue()
{

}

void ELitTrue::accept(Visitor *v)
{
  v->visitELitTrue(this);
}

ELitTrue *ELitTrue::clone() const
{
  return new ELitTrue(*this);
}



/********************   ELitFalse    ********************/
ELitFalse::ELitFalse()
{

}

ELitFalse::ELitFalse(const ELitFalse & other)
{

}

ELitFalse &ELitFalse::operator=(const ELitFalse & other)
{
  ELitFalse tmp(other);
  swap(tmp);
  return *this;
}

void ELitFalse::swap(ELitFalse & other)
{

}

ELitFalse::~ELitFalse()
{

}

void ELitFalse::accept(Visitor *v)
{
  v->visitELitFalse(this);
}

ELitFalse *ELitFalse::clone() const
{
  return new ELitFalse(*this);
}



/********************   EString    ********************/
EString::EString(String p1)
{
  string_ = p1;

}

EString::EString(const EString & other)
{
  string_ = other.string_;

}

EString &EString::operator=(const EString & other)
{
  EString tmp(other);
  swap(tmp);
  return *this;
}

void EString::swap(EString & other)
{
  std::swap(string_, other.string_);

}

EString::~EString()
{

}

void EString::accept(Visitor *v)
{
  v->visitEString(this);
}

EString *EString::clone() const
{
  return new EString(*this);
}



/********************   ENeg    ********************/
ENeg::ENeg(Exp *p1)
{
  exp_ = p1;

}

ENeg::ENeg(const ENeg & other)
{
  exp_ = other.exp_->clone();

}

ENeg &ENeg::operator=(const ENeg & other)
{
  ENeg tmp(other);
  swap(tmp);
  return *this;
}

void ENeg::swap(ENeg & other)
{
  std::swap(exp_, other.exp_);

}

ENeg::~ENeg()
{
  delete(exp_);

}

void ENeg::accept(Visitor *v)
{
  v->visitENeg(this);
}

ENeg *ENeg::clone() const
{
  return new ENeg(*this);
}



/********************   ENot    ********************/
ENot::ENot(Exp *p1)
{
  exp_ = p1;

}

ENot::ENot(const ENot & other)
{
  exp_ = other.exp_->clone();

}

ENot &ENot::operator=(const ENot & other)
{
  ENot tmp(other);
  swap(tmp);
  return *this;
}

void ENot::swap(ENot & other)
{
  std::swap(exp_, other.exp_);

}

ENot::~ENot()
{
  delete(exp_);

}

void ENot::accept(Visitor *v)
{
  v->visitENot(this);
}

ENot *ENot::clone() const
{
  return new ENot(*this);
}



/********************   EMul    ********************/
EMul::EMul(Exp *p1, MulOp *p2, Exp *p3)
{
  exp_1 = p1;
  mulop_ = p2;
  exp_2 = p3;

}

EMul::EMul(const EMul & other)
{
  exp_1 = other.exp_1->clone();
  mulop_ = other.mulop_->clone();
  exp_2 = other.exp_2->clone();

}

EMul &EMul::operator=(const EMul & other)
{
  EMul tmp(other);
  swap(tmp);
  return *this;
}

void EMul::swap(EMul & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(mulop_, other.mulop_);
  std::swap(exp_2, other.exp_2);

}

EMul::~EMul()
{
  delete(exp_1);
  delete(mulop_);
  delete(exp_2);

}

void EMul::accept(Visitor *v)
{
  v->visitEMul(this);
}

EMul *EMul::clone() const
{
  return new EMul(*this);
}



/********************   EAdd    ********************/
EAdd::EAdd(Exp *p1, AddOp *p2, Exp *p3)
{
  exp_1 = p1;
  addop_ = p2;
  exp_2 = p3;

}

EAdd::EAdd(const EAdd & other)
{
  exp_1 = other.exp_1->clone();
  addop_ = other.addop_->clone();
  exp_2 = other.exp_2->clone();

}

EAdd &EAdd::operator=(const EAdd & other)
{
  EAdd tmp(other);
  swap(tmp);
  return *this;
}

void EAdd::swap(EAdd & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(addop_, other.addop_);
  std::swap(exp_2, other.exp_2);

}

EAdd::~EAdd()
{
  delete(exp_1);
  delete(addop_);
  delete(exp_2);

}

void EAdd::accept(Visitor *v)
{
  v->visitEAdd(this);
}

EAdd *EAdd::clone() const
{
  return new EAdd(*this);
}



/********************   ERel    ********************/
ERel::ERel(Exp *p1, RelOp *p2, Exp *p3)
{
  exp_1 = p1;
  relop_ = p2;
  exp_2 = p3;

}

ERel::ERel(const ERel & other)
{
  exp_1 = other.exp_1->clone();
  relop_ = other.relop_->clone();
  exp_2 = other.exp_2->clone();

}

ERel &ERel::operator=(const ERel & other)
{
  ERel tmp(other);
  swap(tmp);
  return *this;
}

void ERel::swap(ERel & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(relop_, other.relop_);
  std::swap(exp_2, other.exp_2);

}

ERel::~ERel()
{
  delete(exp_1);
  delete(relop_);
  delete(exp_2);

}

void ERel::accept(Visitor *v)
{
  v->visitERel(this);
}

ERel *ERel::clone() const
{
  return new ERel(*this);
}



/********************   EAnd    ********************/
EAnd::EAnd(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

EAnd::EAnd(const EAnd & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

EAnd &EAnd::operator=(const EAnd & other)
{
  EAnd tmp(other);
  swap(tmp);
  return *this;
}

void EAnd::swap(EAnd & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

EAnd::~EAnd()
{
  delete(exp_1);
  delete(exp_2);

}

void EAnd::accept(Visitor *v)
{
  v->visitEAnd(this);
}

EAnd *EAnd::clone() const
{
  return new EAnd(*this);
}



/********************   EOr    ********************/
EOr::EOr(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

EOr::EOr(const EOr & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

EOr &EOr::operator=(const EOr & other)
{
  EOr tmp(other);
  swap(tmp);
  return *this;
}

void EOr::swap(EOr & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

EOr::~EOr()
{
  delete(exp_1);
  delete(exp_2);

}

void EOr::accept(Visitor *v)
{
  v->visitEOr(this);
}

EOr *EOr::clone() const
{
  return new EOr(*this);
}



/********************   ETyped    ********************/
ETyped::ETyped(Exp *p1, Type *p2, Char p3)
{
  exp_ = p1;
  type_ = p2;
  char_ = p3;

}

ETyped::ETyped(const ETyped & other)
{
  exp_ = other.exp_->clone();
  type_ = other.type_->clone();
  char_ = other.char_;

}

ETyped &ETyped::operator=(const ETyped & other)
{
  ETyped tmp(other);
  swap(tmp);
  return *this;
}

void ETyped::swap(ETyped & other)
{
  std::swap(exp_, other.exp_);
  std::swap(type_, other.type_);
  std::swap(char_, other.char_);

}

ETyped::~ETyped()
{
  delete(exp_);
  delete(type_);

}

void ETyped::accept(Visitor *v)
{
  v->visitETyped(this);
}

ETyped *ETyped::clone() const
{
  return new ETyped(*this);
}



/********************   EIndex    ********************/
EIndex::EIndex(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

EIndex::EIndex(const EIndex & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

EIndex &EIndex::operator=(const EIndex & other)
{
  EIndex tmp(other);
  swap(tmp);
  return *this;
}

void EIndex::swap(EIndex & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

EIndex::~EIndex()
{
  delete(exp_1);
  delete(exp_2);

}

void EIndex::accept(Visitor *v)
{
  v->visitEIndex(this);
}

EIndex *EIndex::clone() const
{
  return new EIndex(*this);
}



/********************   EAllocate    ********************/
EAllocate::EAllocate(Type *p1, ListLength *p2)
{
  type_ = p1;
  listlength_ = p2;

}

EAllocate::EAllocate(const EAllocate & other)
{
  type_ = other.type_->clone();
  listlength_ = other.listlength_->clone();

}

EAllocate &EAllocate::operator=(const EAllocate & other)
{
  EAllocate tmp(other);
  swap(tmp);
  return *this;
}

void EAllocate::swap(EAllocate & other)
{
  std::swap(type_, other.type_);
  std::swap(listlength_, other.listlength_);

}

EAllocate::~EAllocate()
{
  delete(type_);
  delete(listlength_);

}

void EAllocate::accept(Visitor *v)
{
  v->visitEAllocate(this);
}

EAllocate *EAllocate::clone() const
{
  return new EAllocate(*this);
}



/********************   EDot    ********************/
EDot::EDot(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

EDot::EDot(const EDot & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

EDot &EDot::operator=(const EDot & other)
{
  EDot tmp(other);
  swap(tmp);
  return *this;
}

void EDot::swap(EDot & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

EDot::~EDot()
{
  delete(exp_1);
  delete(exp_2);

}

void EDot::accept(Visitor *v)
{
  v->visitEDot(this);
}

EDot *EDot::clone() const
{
  return new EDot(*this);
}



/********************   ENull    ********************/
ENull::ENull(Type *p1)
{
  type_ = p1;

}

ENull::ENull(const ENull & other)
{
  type_ = other.type_->clone();

}

ENull &ENull::operator=(const ENull & other)
{
  ENull tmp(other);
  swap(tmp);
  return *this;
}

void ENull::swap(ENull & other)
{
  std::swap(type_, other.type_);

}

ENull::~ENull()
{
  delete(type_);

}

void ENull::accept(Visitor *v)
{
  v->visitENull(this);
}

ENull *ENull::clone() const
{
  return new ENull(*this);
}



/********************   EDeref    ********************/
EDeref::EDeref(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

EDeref::EDeref(const EDeref & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

EDeref &EDeref::operator=(const EDeref & other)
{
  EDeref tmp(other);
  swap(tmp);
  return *this;
}

void EDeref::swap(EDeref & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

EDeref::~EDeref()
{
  delete(exp_1);
  delete(exp_2);

}

void EDeref::accept(Visitor *v)
{
  v->visitEDeref(this);
}

EDeref *EDeref::clone() const
{
  return new EDeref(*this);
}



/********************   ECast    ********************/
ECast::ECast(Exp *p1, Type *p2)
{
  exp_ = p1;
  type_ = p2;

}

ECast::ECast(const ECast & other)
{
  exp_ = other.exp_->clone();
  type_ = other.type_->clone();

}

ECast &ECast::operator=(const ECast & other)
{
  ECast tmp(other);
  swap(tmp);
  return *this;
}

void ECast::swap(ECast & other)
{
  std::swap(exp_, other.exp_);
  std::swap(type_, other.type_);

}

ECast::~ECast()
{
  delete(exp_);
  delete(type_);

}

void ECast::accept(Visitor *v)
{
  v->visitECast(this);
}

ECast *ECast::clone() const
{
  return new ECast(*this);
}



/********************   OPlus    ********************/
OPlus::OPlus()
{

}

OPlus::OPlus(const OPlus & other)
{

}

OPlus &OPlus::operator=(const OPlus & other)
{
  OPlus tmp(other);
  swap(tmp);
  return *this;
}

void OPlus::swap(OPlus & other)
{

}

OPlus::~OPlus()
{

}

void OPlus::accept(Visitor *v)
{
  v->visitOPlus(this);
}

OPlus *OPlus::clone() const
{
  return new OPlus(*this);
}



/********************   OMinus    ********************/
OMinus::OMinus()
{

}

OMinus::OMinus(const OMinus & other)
{

}

OMinus &OMinus::operator=(const OMinus & other)
{
  OMinus tmp(other);
  swap(tmp);
  return *this;
}

void OMinus::swap(OMinus & other)
{

}

OMinus::~OMinus()
{

}

void OMinus::accept(Visitor *v)
{
  v->visitOMinus(this);
}

OMinus *OMinus::clone() const
{
  return new OMinus(*this);
}



/********************   OTimes    ********************/
OTimes::OTimes()
{

}

OTimes::OTimes(const OTimes & other)
{

}

OTimes &OTimes::operator=(const OTimes & other)
{
  OTimes tmp(other);
  swap(tmp);
  return *this;
}

void OTimes::swap(OTimes & other)
{

}

OTimes::~OTimes()
{

}

void OTimes::accept(Visitor *v)
{
  v->visitOTimes(this);
}

OTimes *OTimes::clone() const
{
  return new OTimes(*this);
}



/********************   ODiv    ********************/
ODiv::ODiv()
{

}

ODiv::ODiv(const ODiv & other)
{

}

ODiv &ODiv::operator=(const ODiv & other)
{
  ODiv tmp(other);
  swap(tmp);
  return *this;
}

void ODiv::swap(ODiv & other)
{

}

ODiv::~ODiv()
{

}

void ODiv::accept(Visitor *v)
{
  v->visitODiv(this);
}

ODiv *ODiv::clone() const
{
  return new ODiv(*this);
}



/********************   OMod    ********************/
OMod::OMod()
{

}

OMod::OMod(const OMod & other)
{

}

OMod &OMod::operator=(const OMod & other)
{
  OMod tmp(other);
  swap(tmp);
  return *this;
}

void OMod::swap(OMod & other)
{

}

OMod::~OMod()
{

}

void OMod::accept(Visitor *v)
{
  v->visitOMod(this);
}

OMod *OMod::clone() const
{
  return new OMod(*this);
}



/********************   OLt    ********************/
OLt::OLt()
{

}

OLt::OLt(const OLt & other)
{

}

OLt &OLt::operator=(const OLt & other)
{
  OLt tmp(other);
  swap(tmp);
  return *this;
}

void OLt::swap(OLt & other)
{

}

OLt::~OLt()
{

}

void OLt::accept(Visitor *v)
{
  v->visitOLt(this);
}

OLt *OLt::clone() const
{
  return new OLt(*this);
}



/********************   OLe    ********************/
OLe::OLe()
{

}

OLe::OLe(const OLe & other)
{

}

OLe &OLe::operator=(const OLe & other)
{
  OLe tmp(other);
  swap(tmp);
  return *this;
}

void OLe::swap(OLe & other)
{

}

OLe::~OLe()
{

}

void OLe::accept(Visitor *v)
{
  v->visitOLe(this);
}

OLe *OLe::clone() const
{
  return new OLe(*this);
}



/********************   OGt    ********************/
OGt::OGt()
{

}

OGt::OGt(const OGt & other)
{

}

OGt &OGt::operator=(const OGt & other)
{
  OGt tmp(other);
  swap(tmp);
  return *this;
}

void OGt::swap(OGt & other)
{

}

OGt::~OGt()
{

}

void OGt::accept(Visitor *v)
{
  v->visitOGt(this);
}

OGt *OGt::clone() const
{
  return new OGt(*this);
}



/********************   OGe    ********************/
OGe::OGe()
{

}

OGe::OGe(const OGe & other)
{

}

OGe &OGe::operator=(const OGe & other)
{
  OGe tmp(other);
  swap(tmp);
  return *this;
}

void OGe::swap(OGe & other)
{

}

OGe::~OGe()
{

}

void OGe::accept(Visitor *v)
{
  v->visitOGe(this);
}

OGe *OGe::clone() const
{
  return new OGe(*this);
}



/********************   OEq    ********************/
OEq::OEq()
{

}

OEq::OEq(const OEq & other)
{

}

OEq &OEq::operator=(const OEq & other)
{
  OEq tmp(other);
  swap(tmp);
  return *this;
}

void OEq::swap(OEq & other)
{

}

OEq::~OEq()
{

}

void OEq::accept(Visitor *v)
{
  v->visitOEq(this);
}

OEq *OEq::clone() const
{
  return new OEq(*this);
}



/********************   ONe    ********************/
ONe::ONe()
{

}

ONe::ONe(const ONe & other)
{

}

ONe &ONe::operator=(const ONe & other)
{
  ONe tmp(other);
  swap(tmp);
  return *this;
}

void ONe::swap(ONe & other)
{

}

ONe::~ONe()
{

}

void ONe::accept(Visitor *v)
{
  v->visitONe(this);
}

ONe *ONe::clone() const
{
  return new ONe(*this);
}



/********************   LLength    ********************/
LLength::LLength(Exp *p1)
{
  exp_ = p1;

}

LLength::LLength(const LLength & other)
{
  exp_ = other.exp_->clone();

}

LLength &LLength::operator=(const LLength & other)
{
  LLength tmp(other);
  swap(tmp);
  return *this;
}

void LLength::swap(LLength & other)
{
  std::swap(exp_, other.exp_);

}

LLength::~LLength()
{
  delete(exp_);

}

void LLength::accept(Visitor *v)
{
  v->visitLLength(this);
}

LLength *LLength::clone() const
{
  return new LLength(*this);
}



/********************   SStruct    ********************/
SStruct::SStruct(Ident p1, ListField *p2)
{
  ident_ = p1;
  listfield_ = p2;

}

SStruct::SStruct(const SStruct & other)
{
  ident_ = other.ident_;
  listfield_ = other.listfield_->clone();

}

SStruct &SStruct::operator=(const SStruct & other)
{
  SStruct tmp(other);
  swap(tmp);
  return *this;
}

void SStruct::swap(SStruct & other)
{
  std::swap(ident_, other.ident_);
  std::swap(listfield_, other.listfield_);

}

SStruct::~SStruct()
{
  delete(listfield_);

}

void SStruct::accept(Visitor *v)
{
  v->visitSStruct(this);
}

SStruct *SStruct::clone() const
{
  return new SStruct(*this);
}



/********************   FField    ********************/
FField::FField(Type *p1, Ident p2)
{
  type_ = p1;
  ident_ = p2;

}

FField::FField(const FField & other)
{
  type_ = other.type_->clone();
  ident_ = other.ident_;

}

FField &FField::operator=(const FField & other)
{
  FField tmp(other);
  swap(tmp);
  return *this;
}

void FField::swap(FField & other)
{
  std::swap(type_, other.type_);
  std::swap(ident_, other.ident_);

}

FField::~FField()
{
  delete(type_);

}

void FField::accept(Visitor *v)
{
  v->visitFField(this);
}

FField *FField::clone() const
{
  return new FField(*this);
}



/********************   MField    ********************/
MField::MField(Field *p1)
{
  field_ = p1;

}

MField::MField(const MField & other)
{
  field_ = other.field_->clone();

}

MField &MField::operator=(const MField & other)
{
  MField tmp(other);
  swap(tmp);
  return *this;
}

void MField::swap(MField & other)
{
  std::swap(field_, other.field_);

}

MField::~MField()
{
  delete(field_);

}

void MField::accept(Visitor *v)
{
  v->visitMField(this);
}

MField *MField::clone() const
{
  return new MField(*this);
}



/********************   MFun    ********************/
MFun::MFun(Type *p1, Ident p2, ListArg *p3, ListStm *p4)
{
  type_ = p1;
  ident_ = p2;
  listarg_ = p3;
  liststm_ = p4;

}

MFun::MFun(const MFun & other)
{
  type_ = other.type_->clone();
  ident_ = other.ident_;
  listarg_ = other.listarg_->clone();
  liststm_ = other.liststm_->clone();

}

MFun &MFun::operator=(const MFun & other)
{
  MFun tmp(other);
  swap(tmp);
  return *this;
}

void MFun::swap(MFun & other)
{
  std::swap(type_, other.type_);
  std::swap(ident_, other.ident_);
  std::swap(listarg_, other.listarg_);
  std::swap(liststm_, other.liststm_);

}

MFun::~MFun()
{
  delete(type_);
  delete(listarg_);
  delete(liststm_);

}

void MFun::accept(Visitor *v)
{
  v->visitMFun(this);
}

MFun *MFun::clone() const
{
  return new MFun(*this);
}




/********************   ListDef    ********************/

void ListDef::accept(Visitor *v)
{
  v->visitListDef(this);
}


ListDef *ListDef::clone() const
{
  return new ListDef(*this);
}


/********************   ListArg    ********************/

void ListArg::accept(Visitor *v)
{
  v->visitListArg(this);
}


ListArg *ListArg::clone() const
{
  return new ListArg(*this);
}


/********************   ListStm    ********************/

void ListStm::accept(Visitor *v)
{
  v->visitListStm(this);
}


ListStm *ListStm::clone() const
{
  return new ListStm(*this);
}


/********************   ListDec    ********************/

void ListDec::accept(Visitor *v)
{
  v->visitListDec(this);
}


ListDec *ListDec::clone() const
{
  return new ListDec(*this);
}


/********************   ListType    ********************/

void ListType::accept(Visitor *v)
{
  v->visitListType(this);
}


ListType *ListType::clone() const
{
  return new ListType(*this);
}


/********************   ListExp    ********************/

void ListExp::accept(Visitor *v)
{
  v->visitListExp(this);
}


ListExp *ListExp::clone() const
{
  return new ListExp(*this);
}


/********************   ListLength    ********************/

void ListLength::accept(Visitor *v)
{
  v->visitListLength(this);
}


ListLength *ListLength::clone() const
{
  return new ListLength(*this);
}


/********************   ListField    ********************/

void ListField::accept(Visitor *v)
{
  v->visitListField(this);
}


ListField *ListField::clone() const
{
  return new ListField(*this);
}


/********************   ListMember    ********************/

void ListMember::accept(Visitor *v)
{
  v->visitListMember(this);
}


ListMember *ListMember::clone() const
{
  return new ListMember(*this);
}



}
